product:
active: true
intents:
    toProduct:
        initial: true
        type: command
        condition: "content == 'toProduct'"
    askProduct:
        type: data
        initial: true
        fallback: false
        classifier:
            nlu: askProduct
    
states:
    showProduct:
        action:
            - name: productOption
            - name: askOption
        transition:
            productDetail:
                condition: 'payload.type = "product"'
            showProduct:
                fallback: true
    
    productDetail:
        action:
            - name: showDetail
            - name: toProduct
        transition: 
            productInfo: 'payload.type = "productDetail"'
            productDetail:
                fallback: true
            

action:
    askOption:
        type: text
        text: "Silahkan klik produk yang ingin anda lihat detailnya."
    productOption:
      type: template
      option:
        type: carousel
        items:
            - title: Galaxy S
              text: Galaxy S
              thumbnailImageUrl: 'https://images.samsung.com/is/image/samsung/p5/global/mkt/unpacked201802/pcdpfs/smartphone-galaxy-star-type4.png?$ORIGIN_PNG$'
              actions:
                  - 
                    type: postback
                    label: galaxy s
                    payload:
                        type: product
                        product: Galaxy S

            - title: Galaxy Note
              text: Galaxy Note
              thumbnailImageUrl: 'https://images.samsung.com/is/image/samsung/p5/global/mkt/unpacked201708/pcd/smartphones-galaxy-great-black.png?$ORIGIN_PNG$'
              actions:
                  - 
                    type: postback
                    label: galaxy note
                    payload:
                        type: product
                        product: Galaxy Note

            - title: Galaxy A
              text: galaxy a
              thumbnailImageUrl: 'https://images.samsung.com/is/image/samsung/p5/id/mobile/smartphone-galaxy-pcd-a-series-mobile.png?$ORIGIN_PNG$'
              actions:
                  - 
                    type: postback
                    label: galaxy a
                    payload:
                        type: product
                        product: Galaxy A

            - title: Galaxy J
              text: galaxy j
              thumbnailImageUrl: 'https://images.samsung.com/is/image/samsung/p5/id/mobile/smartphone-galaxy-pcd-j-series-mobile.png?$ORIGIN_PNG$'
              actions:
                  - 
                    type: postback
                    label: galaxy j
                    payload:
                        type: product
                        product: Galaxy J
    showDetailS:
      type: template
      option:
        type: carousel
        items:
            - title: Galaxy S9
              text: Galaxy S9
              thumbnailImageUrl: ''
              actions:
                  - 
                    type: postback
                    label: Galaxy S9
                    payload:
                        type: product
                        product: Galaxy S9

            - title: Galaxy S9+
              text: Galaxy S9+
              thumbnailImageUrl: ''
              actions:
                  - 
                    type: postback
                    label: Galaxy S9+
                    payload:
                        type: product
                        product: Galaxy S9+

            - title: Galaxy S7 Edge
              text: Galaxy S7 Edge
              thumbnailImageUrl: ''
              actions:
                  - 
                    type: postback
                    label: Galaxy S7 Edge
                    payload:
                        type: product
                        product: Galaxy S7 Edge
        
    done:
        type: text
        options:
            text: "Berikut spesifikasi dari handphone ${payload.type} :"
    toFallback: 
        type: command
        options:
            command: toFallback

